# Generated by Django 4.2.3 on 2023-08-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main2", "0002_cartorder_wishlist_useraddressbook_productreview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="qty",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
