# Generated by Django 4.2.3 on 2023-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main2", "0003_productattribute_qty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorderitems", options={"verbose_name_plural": "Order Items"},
        ),
        migrations.AddField(
            model_name="cartorder",
            name="qty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartorder",
            name="qty_remaining",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Waiting Payment", "waiting"),
                    ("Ready to ship", "ready"),
                    ("Shipped", "shipped"),
                    ("Complete", "complete"),
                    ("Cancel", "cancel"),
                ],
                default="Waiting Payment",
                max_length=150,
            ),
        ),
    ]
