# Generated by Django 4.2.3 on 2023-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main2", "0004_alter_cartorderitems_options_cartorder_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder", name="qty", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="qty_remaining",
            field=models.IntegerField(null=True),
        ),
    ]
