# Generated by Django 4.2.3 on 2023-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
